### ISSUE TITLE
Consistent use of properties

### ISSUE THREAD

**Issue by ashjbarnes** [CROCODILE-CESM/regional-mom6#14]
@manishvenu has made a start on setting properties corresponding to each forcing file. For example, calling 

`expt.initial_condition` 

now opens the initial conditions from the input directory. We should stop saving `self.bathymetry` upon generating bathymetry to minimise memory footprint, and instead have a property for each of the files in the input directory which simply opens existing dataarrays, or prints an error message if they're not found.

This would require renaming the current `bathymetry_property` in #12 to `bathymetry`, splitting the `initial_condition` into the tracer and velocity and eta components, and deleting the existing `bathymetry` property that is saved automatically upon generating bathymetry.

**Comment by ashjbarnes** [comment]
Just to add to this: what would be REALLY cool is we also have custom plot functions. For example, if you called 

`expt.bathymetry`, it would return the xarray dataset containing the ` bathymetry.nc` file. But if you were to go `expt.plot.bathymetry`, it automatically plots it with `cartopy` to produce something like [this](https://github.com/jsimkins2/nwa25/blob/main/misc/images/nwa25_bathymetry.png?raw=true). Ideally do the same thing for initial conditions, vertical coordinate, maybe even boundaries if we can find a nice way to plot them

**Comment by manishvenu** [comment]
PR #23 closes this
