### ISSUE TITLE
Creating a dev environment?

### ISSUE THREAD

**Issue by alperaltuntas** [CROCODILE-CESM/regional-mom6#18]
Sorry if this is already in the docs, but what is the proper way to create a development environment?

I attempted create an env with below commands but ended up with missing libraries like dask, xarray:

git clone https://github.com/CROCODILE-CESM/regional-mom6
cd regional-mom6
conda env create -f environment-ci.yml

**Comment by ashjbarnes** [comment]
* make new conda env * 

`mamba install esmf`
`git clone regional_mom6 && cd PATH`
`pip install -e .` 

This gives an editable install. I find editable install more robust with pip than with mamba, but you can't install esmf via pip

**Comment by ashjbarnes** [comment]
@alperaltuntas if this works we should put this explicitly in the README!

**Comment by alperaltuntas** [comment]
I got: 

```
      ModuleNotFoundError: No module named 'mpi4py'
      [end of output]
```

commit hash: f562b1

**Comment by alperaltuntas** [comment]
Got the same error again when I attempted a fresh installation.

**Comment by ashjbarnes** [comment]
What about with the conda install, same as the CI uses? Might be somehow tied to pip

**Comment by alperaltuntas** [comment]
I manually conda-installed netCDF4, which apperaently requires mpi4py, and it seems to have passed that step and continuing with the install just fine so far.

**Comment by alperaltuntas** [comment]
I got another error later in numba installation:

```
      RuntimeError: Cannot install on Python version 3.13.0; only versions >=3.9,<3.13 are supported.
      [end of output]
```

**Comment by manishvenu** [comment]
> I got another error later in numba installation:
> 
> ```
>       RuntimeError: Cannot install on Python version 3.13.0; only versions >=3.9,<3.13 are supported.
>       [end of output]
> ```

Huh, that's interesting, are you installing it on Python 3.13? Other than dropping the version trying [this yml ](https://github.com/CROCODILE-CESM/nwa12_v0/blob/add_freds_nwa12_notebooks/rm6_env.yml)file might work as well. It has everything except regional-mom6 itself, so adding a `sys.path.insert(0,...)` than importing regional_mom6 should work

**Comment by manishvenu** [comment]
Main Project issue for this is https://github.com/CROCODILE-CESM/crocodile-regional-ruckus/issues/5

**Comment by manishvenu** [comment]
Solved.
