### ISSUE TITLE
Automatically populate MOM_input when number of boundaries < 4

### ISSUE THREAD

**Issue by ashjbarnes** [CROCODILE-CESM/regional-mom6#8]
At the moment, the "rectangular boundaries" method lets you specify which cardinal directions you want for your boundaries. If you delete one, and have say `["south","east","north"]`, the regridder will still work fine but the `MOM_input` file will not be updated to reflect this. 

A way to do this could be to remove the OBC stuff from the MOM_input entirely and migrate it all to override. The `setup_rundir` method then populates `MOM_override` with all of the specific boundary data you need for the experiment, including tides. This plays into what @manishvenu suggested the other day, of having all of the `regional-mom6` setup information in one place all together. This could be a JSON string characterising the run, a commented `MOM_override` file, or both

**Comment by manishvenu** [comment]
Yeah, I like this a lot! There's a couple rough functions for the JSON/dictionary stuff that could help [here](https://github.com/manishvenu/regional-mom6/blob/croc_with_req_changes/regional_mom6/regional_mom6.py) called `read_MOM_file` and `write_MOM_file`

**Comment by ashjbarnes** [comment]
oh awesome! I didn't realise you were developing in a personal fork. Do you have the right permissions to make branches directly on CROCODILE?

**Comment by manishvenu** [comment]
I do have those permissions. I just kinda started with a personal fork? Happy to shift over here if that makes dev easier, kinda just made a new fork randomly. Regardless, the personal fork should be pretty synced up with CROCODILE's fork.

**Comment by ashjbarnes** [comment]
yeah no worries whatever's easiest for you :)

**Comment by ashjbarnes** [comment]
I think this is going to be covered by @manishvenu 's work!

**Comment by ashjbarnes** [comment]
This was closed with #12
